### ISSUE TITLE
subprocess

### ISSUE THREAD

**Issue by jambunjo** [hacksmath/RiskMetrics#15]
unable to run due to subprocess import run

**Comment by hacksmath** [comment]
What version of python were you running it with?

**Comment by jambunjo** [comment]
Thanks I got it to work, the problem was that I was using linux and the setup uses /usr/local/bin/python3 and it needed to be /usr/bin/python3, the other part was when I had told it to use python2 because it couldn't find 3 and that's where the subprocess error came from.

**Comment by hacksmath** [comment]
Yes, we need to work on making the procedure less platform specific. Thanks for troubleshooting that.
