### ISSUE TITLE
Unable to run tests

### ISSUE THREAD

**Issue by jambunjo** [hacksmath/RiskMetrics#16]
attempting to run pytest gives the following error:

ImportError while importing test module '/home/jack/Code/RiskMetrics/riskmetrics/test/test_riskmetrics.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
test_riskmetrics.py:5: in <module>
    from unittest.mock import patch, MagicMock
E   ImportError: No module named mock

I also made sure to install MagicMock

**Comment by hacksmath** [comment]
I get this error when running tests with python 2 instead of 3. However, tests have been refactored and no longer require MagicMock.
